### ISSUE TITLE
Forall Typeable is satisfied 

### ISSUE THREAD

**Issue by cchalmers** [ekmett/constraints#10]
Since 7.10 `Typeable` is derived for everything. This means `Forall Typeable = (Typeable A, Typeable B)` is satisfied so you can write

```{.haskell}
import Data.Constraint
import Data.Constraint.Forall

typeable :: a -> Dict (Typeable a)
typeable _ = case inst of Sub d -> d
```

```
> case typeable 'a' of Dict -> typeOf 'a'
A
```

which allows you to write an `unsafeCoerce` without any extensions:

```{.haskell}
import Data.Typeable

unsafeCoerce :: a -> b
unsafeCoerce a = b
  where
    Just b = case typeable a of
      Dict -> case typeable b of
        Dict -> cast a
```

```
> unsafeCoerce 'a'
97
```

**Comment by ekmett** [comment]
This kills Forall.

**Comment by treeowl** [comment]
It should be okay to close this now, I believe. `Forall Typeable` now expands to `Forall_ Typeable`, which entails `Typeable (Skolem Typeable)`. Since `Skolem Typeable` is stuck, it had better not be an instance of any class whatsoever (if it is, I'd consider that a compiler bug).
