### ISSUE TITLE
Consider using AppendSymbol in Data.Constraint.Symbol

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/constraints#100]
Currently, [`Data.Constraint.Symbol`](https://github.com/ekmett/constraints/blob/46e8a62c8a38e9fdb78f372b836e3ddcede25bfa/src/Data/Constraint/Symbol.hs) contains the following:

```hs
type family (++) :: Symbol -> Symbol -> Symbol where

appendSymbol :: (KnownSymbol a, KnownSymbol b) :- KnownSymbol (a ++ b)
appendSymbol = magicSSS (++)

appendUnit1 :: forall a. Dict (("" ++ a) ~ a)
appendUnit1 = axiom

appendUnit2 :: forall a. Dict ((a ++ "") ~ a)
appendUnit2 = axiom

appendAssociates :: forall a b c. Dict (((a ++ b) ++ c) ~ (a ++ (b ++ c)))
appendAssociates = axiom

takeAppendDrop :: forall n a. Dict (Take n a ++ Drop n a ~ a)
takeAppendDrop = axiom
```

This works, but it is somewhat out of sync with modern versions of `GHC.TypeLits`, which provide a magic type family in the same vein as `(++)`, called [`AppendSymbol`](https://hackage.haskell.org/package/base-4.14.0.0/docs/GHC-TypeLits.html#t:AppendSymbol). Really, `constraints` ought to be using `AppendSymbol` instead of `(++)` (the latter predates the former), even though doing so would be a breaking change.

**Comment by kquick** [comment]
Of note is that `AppendSymbol` does not provide `KnownSymbol` witnesses, so it could benefit from the constraints in this package.

**Comment by RyanGlScott** [comment]
I almost discovered a way to avoid this being a breaking change by defining `(++)` as a compatibility shim:

```hs
type a ++ b = AppendSymbol a b
```

Alas, that is ever-so-slightly different from the current definition of `(++)`:

```hs
type family (++) :: Symbol -> Symbol -> Symbol where
```

The difference is that the former definition has an arity of 2, meaning that you must supply it with 2 arguments in order for it to be a well formed type, while the latter definition has arity 0. This means that you can write code like the following with the latter definition, but not the former:

```hs
type App f a b = f a b 
type Blah = App (++) "foo" "bar"
```

Therefore, even if we make `(++)` a compatibility shim, it will still be a breaking change. I still think that this would be a worthwhile change, however, and I doubt that many users are likely to encounter this difference in practice.

**Comment by RyanGlScott** [comment]
See #101.
