### ISSUE TITLE
Build failure with `mtl-2.3`

### ISSUE THREAD

**Issue by andreasabel** [ekmett/constraints#110]
The `ErrorT` instances should be removed in preparation for the upcoming `mtl-2.3` release:
https://github.com/ekmett/constraints/blob/07c239f1e67caa6dd58e8484f6b86caca62aa409/src/Data/Constraint/Lifting.hs#L178-L192

**Comment by RyanGlScott** [comment]
I've uploaded [`constraints-0.13.3`](https://hackage.haskell.org/package/constraints-0.13.3) to Hackage with a more conservative version of the patch in #111 that doesn't require a major version bump. I'll release `constraints-0.14` with #111 proper at some point in the future.
