### ISSUE TITLE
Bottom seems insufficiently general to be useful

### ISSUE THREAD

**Issue by treeowl** [ekmett/constraints#12]
`bottom` demonstrates that a particular unsatisfiable constraint, `() ~ Bool`, entails any constraint. This is not a particularly interesting false constraint, and there doesn't *seem* to be any particularly obvious way to produce it from other false constraints. I don't have anything approaching a full solution, but here are some ideas to think about, based on the notion that if a constraint can prove void, it must be wrong:

```haskell
crazy :: (c => Void) -> c :- d
crazy q = Sub (absurd q)
```

From this, we can recover the `() ~ Bool` idea in a way that can be used much more generally.

```haskell
-- Proof that one type doesn't unify with another
newtype (/=) a b = NE {no :: forall c . (a :~: b) -> c}

-- If two types don't unify, then the assumption that they do entails anything.
hola :: forall a b d . a /= b -> (a ~ b) :- d
hola (NE nope) = crazy $ nope (Refl :: a :~: b)

-- A type useful for proving inequality
data Yeah this that a where
  Yeah1 :: Yeah this that this
  Yeah2 :: (forall b . b) -> Yeah this that that

-- Getting to Yeah
hoop :: forall a b . (a :~: b) -> Yeah a b b
hoop Refl = Yeah1

-- The specific example of `() ~ Bool`, expressed concisely; to prove other inequations,
-- only the type signature needs to be changed.
hum :: () /= Bool
hum = NE $ \ab -> case hoop ab of Yeah2 x -> x
```

**Comment by treeowl** [comment]
Inequations, of course, aren't all that `crazy` can handle, of course. It can also take care of classes that are impossible to implement properly. This perfectly valid example demonstrates that Haskell is a bit strange.

```haskell
blargh :: Integral Integer :- c
blargh = crazy $ case (1 `div` 0 :: Integer) of {}
```

**Comment by treeowl** [comment]
A prettier example:

```haskell
foo :: Bifunctor (->) :- c
foo = crazy $ bimap (const ()) id id ()
```

**Comment by ekmett** [comment]
Alternative colors for the bikeshed for consideration:

```haskell
crazy :: (forall x. c :- x) -> c :- d
crazy x = x

crazy :: (forall x. c => x) -> c :- d
crazy x = Sub x
```

**Comment by treeowl** [comment]
These alternate bikeshed colors seem strictly less convenient, as we discussed. The first one is a triviality, so I see no value in it whatsoever. The second is perhaps more efficient, but it likely pushes the `absurd` application to the caller while making it a bit harder to see from the type what it's for.

**Comment by ekmett** [comment]
After much discussion I think we've converged to a pretty decent design in HEAD. Consequently, closing this out
