### ISSUE TITLE
Show type representation of a, b when Deferrable (a ~ b) fails

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/constraints#29]
When `(Typeable a, Typeable b) => Deferrable (a ~ b)` fails our error is:

```haskell
Nothing -> Left "deferred type equality: type mismatch"
```

but the user may want some information about the types (we already have their `Typeable` instances), so why not write:

```haskell
Nothing   -> Left $
  printf "deferred type equality: type mismatch between ‘%s’ and ‘%s’" (showTr @a) (showTr @b)
  where
    showTr :: ∀t. Typeable t => String
    showTr = show (typeRep @_ @t Proxy)

```

**Comment by Icelandjack** [comment]
Couldn't you also accumulate the errors in `Deferrable (a, b)`, `Deferrable (a, b, c)`

**Comment by ekmett** [comment]
The former sounds good to me. The latter sounds interesting and I'd happily take a patch that did it.

**Comment by ekmett** [comment]
I've implemented the former. The latter may require more thought, as the API would likely need to change to gain a good way to accumulate multiple messages.
