### ISSUE TITLE
`Deferrable (a ~~ b)` instance?

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/constraints#40]
Any use for

```haskell
data (a::k1) :~~: (b::k2) where
  HRefl :: a :~~: a

instance (Typeable k1, Typeable k2, Typeable (a::k1), Typeable (b::k2)) => Deferrable (a ~~ b) where
  deferEither _ r = case cast (HRefl :: a :~~: a) :: Maybe (a :~~: b) of
    Just HRefl -> Right r
    Nothing    -> Left ...
```

in lieu of `Deferrable (a ~ b)`, of which I believe it is a special case (`k1 ~ Type, k2 ~ Type`)

**Comment by Icelandjack** [comment]
Or at least making it polykinded `k1 ~ k2`

**Comment by ekmett** [comment]
It'd have to go in as an instance in 8+ where it can be defined. Does 8 give us :~~: or do we have to define it ourselves? I saw Richard talk about adding it, but not that it was in.

**Comment by ekmett** [comment]
I may leave this one open rather than say we should adopt it today. It has the downside that it only works with 8+.

**Comment by ekmett** [comment]
On the plus side, it is at ~~, not ~, so it doesn't conflict with the instance we have, no?

**Comment by ekmett** [comment]
That would let us adopt it today.

**Comment by RyanGlScott** [comment]
I don't believe `base` currently defines `:~~:`. Then again, `constraints` [redefines `:~:`](https://github.com/ekmett/constraints/blob/767929d1514370a3810e1291016de596ef743bd8/src/Data/Constraint/Deferrable.hs#L72-L75), so I suppose it could redefine `:~~:` as well.

**Comment by ekmett** [comment]
Hrmm. We should modify the definition of :~: to default to the base version when on modern GHCs. I'd forgotten I did that. We can do the same with (:~~:).

**Comment by Icelandjack** [comment]
I think `(:~~:)` is slated to be added to `Data.Type.Equality` next GHC release. Will respond to other comments in a bit

**Comment by oerjan** [comment]
It redefines it, but only for internal use. I assume if it *had* exported it, you would already have applied CPP to select the base version.

**Comment by ekmett** [comment]
It is in HEAD.
