### ISSUE TITLE
Common name for ‘Sub Dict’

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/constraints#41]
Is there _any_ way to give a common name to `Sub Dict`?

The closest I got was

``` haskell
subdict :: forall a b. a => a :- b
subdict = Sub @a @b (Dict @a)
```

but I couldn't write `refl` in terms of it without a constraint..

``` haskell
refl :: a => a :- a
refl = subdict
```

**Comment by Icelandjack** [comment]
Wait! Does it require [implication constraints](https://ghc.haskell.org/trac/ghc/ticket/5927)?

```haskell
subdict :: forall a b. a `Implies` b => a :- b
subdict = Sub @a @b (Dict @a)
```

That would make sense that `:-` is a reified version of implication constraints like these are reified versions of coercion, constraints, equality, ...

```haskell
Coercion :: Coercible a b => Coercion a b

Dict :: a => Dict a

Refl :: a ~ b => a :~: a

HRefl :: a ~~ b => a :~~: b
```

If so then there is no way to write `subdict` until we get implication constraints, feel free to close this.

**Comment by ekmett** [comment]
There is no way to write this at present.

**Comment by RyanGlScott** [comment]
This is now possible with the WIP `QuantifiedConstraints` branch of GHC:

```haskell
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE QuantifiedConstraints #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
module Foo where

data Dict c where
  Dict :: c => Dict c

newtype a :- b = Sub (a => Dict b)

subdict :: forall a b. (a => b) => a :- b
subdict = Sub (Dict @b)
```

**Comment by ekmett** [comment]
This will probably have to wait until 8.6 or so before it can be added directly to the library. It seems like `QuantifiedConstraints` will miss the 8.4 branch at this point.

**Comment by Icelandjack** [comment]
Can't wait for QC. Going the other way is not possible (`(a :- b) -> Dict (a => b)`) though

**Comment by ekmett** [comment]
Building the other direction is a messy exercise in unsafeCoercing enough stuff to produce the right core. It is admissible.

But we could avoid that completely. In the presence of `QuantifiedConstraints` the encoding I use for `(:-)` is suboptimal. Switching from the existing `Sub Dict` encoding to

```haskell
data a :- b where
   Sub :: (a => b) -> a :- b
```

or, equivalently,

```haskell
newtype a :- b = Sub (Dict (a => b))
```

makes this easy though, giving a good reason to favor such an encoding over the current approach going forward.

**Comment by aaronvargo** [comment]
You would still need the unsafeCoercing to construct an `a :- b` from an `a => Dict b` then.

[Here's one way](https://github.com/ekmett/constraints/pull/81#issuecomment-403638363) (I think) to do the unsafeCoercing (using the old definition of `(:-)`)

I vote for naming `subdict` `implied`:

```
implied :: forall a b. (a => b) => a :- b
```

**Comment by RyanGlScott** [comment]
I am also in favor of adding `implied`.

The change to `(:-)` proposed in https://github.com/ekmett/constraints/issues/41#issuecomment-372562055 is interesting, but it would require `constraints` to cut off support for pre-8.6 versions of GHC. (Unless we were to employ some sort of CPP-based backwards-compatibility hack, which doesn't sound appealing.) Until then, adding `implied` should be uncontroversial.
