### ISSUE TITLE
The undefined breaks the constraints system. This is a bug or a feature?

### ISSUE THREAD

**Issue by SkorikGG** [ekmett/constraints#44]
The following code compiles without any warnings:
----------------------------------------------------------------------------------------------------------
```
{-# LANGUAGE TypeOperators,ScopedTypeVariables,DataKinds,TypeOperators,TypeFamilies #-}
module Main (main) where

import Data.Constraint
import GHC.TypeLits
import Data.Proxy

showAdd :: forall a. Show a => a -> a-> a
showAdd x y = (x :: a) + y \\ (undefined :: (Show a):-(Num a))

typeSubt :: (b<=a) => Proxy a -> Proxy b -> Proxy (a-b)
typeSubt _ _ = Proxy

badSubt :: Proxy a -> Proxy b -> Proxy (a-b)
badSubt (pa::Proxy a) (pb :: Proxy b) = typeSubt pa pb \\ (undefined :: ():-(b<=a))

main = do
    let
        Just s2 = someNatVal 2
        Just s3 = someNatVal 3
    case (s2,s3) of
        (SomeNat (pa :: Proxy a),SomeNat (pb :: Proxy b)) ->
                print $ badSubt pa pb -- No exception!
    putStrLn $ "2" `showAdd` "2"   -- exception Prelude.undefined
```
--------------------------------------------------------------------------------------------------------
Tested on constraints version 0.8, ghc version 7.10.3

**Comment by Lysxia** [comment]
I was confused about the first `print` not throwing anything, but the `Show` instance of `Proxy` is actually non-strict, which means that this call to `badSubst` is indeed not evaluated. (Source: http://hackage.haskell.org/package/base-4.9.0.0/docs/src/Data.Proxy.html#line-48)

It's part of Haskell's design that `undefined :: a` is a value of any type, which can thus be used in place of any expression. The strong type guarantees of Haskell assume good faith on the part of the programmer, who is not supposed to use the `undefined` backdoor in places where the value might be evaluated.

It's not a bug, nor a feature of `constraints`.

**Comment by SkorikGG** [comment]
Still, the fact that in spite of its contract, you can call the function without any exception  is very counterintuitive and can lead to unexpected results. For example, look at the result of this program:

`{-# LANGUAGE TypeOperators,ScopedTypeVariables,DataKinds,TypeOperators,TypeFamilies #-}
module Main (main) where

import Data.Constraint
import Unsafe.Coerce
import GHC.TypeLits
import Data.Proxy
import Control.Exception

typeSubt :: (b<=a) => Proxy a -> Proxy b -> Proxy (a-b)
typeSubt Proxy Proxy = Proxy

badSubt :: Proxy a -> Proxy b -> Proxy (a-b)
badSubt (pa :: Proxy a) (pb :: Proxy b) = typeSubt pa pb \\ (undefined :: ():-(b<=a))

main = do
    let
        n2=2
        n3=3
        Just s2 = someNatVal 2
        Just s3 = someNatVal 3
    case (s2,s3) of
        (SomeNat (pa :: Proxy a),SomeNat (pb :: Proxy b)) -> do
            s<-catch (evaluate $ show (badSubt pa pb)) (\(e :: ErrorCall)->return "Exception")
            case s of
                "Proxy" -> print $ show n2 ++ " is greater than " ++ show n3
                "Exception" -> print $ show n2 ++ " is less than " ++ show n3`

**Comment by Lysxia** [comment]
Any haskeller should know that `undefined` is dangerous, `unsafeCoerce` is less well known but its name and location say enough. The point of these is to tell the compiler "get out of the way, I know what I'm doing." so a warning would be counterproductive.

In what way is this an issue specific to `constraints`?

    import Data.Proxy
    main = print (undefined :: Proxy ())

**Comment by ekmett** [comment]
Everything there seems to be working as intended. The second argument to \\ is forced when and if the result is actually forced. Your intuition is flawed here. If you replace Proxy with a stricter variant your code performs as you'd expect.

```haskell
{-# LANGUAGE TypeOperators,ScopedTypeVariables,DataKinds,TypeOperators,TypeFamilies,PolyKinds #-}
module Main (main) where

import Data.Constraint
import GHC.TypeLits
import Data.Proxy

data StrictProxy a = StrictProxy
  deriving Show

showAdd :: forall a. Show a => a -> a-> a
showAdd x y = (x :: a) + y \\ (undefined :: (Show a):-(Num a))

typeSubt :: (b<=a) => Proxy a -> Proxy b -> StrictProxy (a-b)
typeSubt _ _ = StrictProxy

badSubt :: Proxy a -> Proxy b -> StrictProxy (a-b)
badSubt (pa::Proxy a) (pb :: Proxy b) = typeSubt pa pb \\ (undefined :: ():-(b<=a))

main = do
    let
        Just s2 = someNatVal 2
        Just s3 = someNatVal 3
    case (s2,s3) of
        (SomeNat (pa :: Proxy a),SomeNat (pb :: Proxy b)) ->
                print $ badSubt pa pb -- No exception!
```

This isn't unsafe, its just a combination of features not working the way you expect.

Unsafety would be if we just "trusted" the witness we passed to the right hand side of (\\) without evaluating it somehow, and you could then derive actual (~)'s between disparate types and then obtain segfaults, rather than bottoms.
