### ISSUE TITLE
Getting seg fault while trying to use appendSymbol

### ISSUE THREAD

**Issue by mageshb** [ekmett/constraints#50]
Here is test code

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
module Lib
    ( someFunc
    ) where

import Data.Constraint
import Data.Constraint.Symbol
import Data.Proxy
import GHC.TypeLits

someFunc :: IO ()
someFunc = do
  putStrLn $ ((symbolVal (Proxy :: Proxy ("Foo" ++ "Bar")))
              \\ (appendSymbol :: ((KnownSymbol "Foo", KnownSymbol "Bar") :- KnownSymbol ("Foo" ++ "Bar")))
             )
```

It core dumped in GHC 8.0.1 as well in 8.0.2
Is it a bug or am I missing something here

**Comment by RyanGlScott** [comment]
It is a bug, and it was fixed upstream in 55836e5a10591418ec44b89b7b39b1639daf68fd. I'll try to get a new release on Hackage soon with this fix.

**Comment by mageshb** [comment]
Thank you @RyanGlScott

**Comment by RyanGlScott** [comment]
I've uploaded [`constraints-0.9.1`](http://hackage.haskell.org/package/constraints-0.9.1) to Hackage with this fix.
