### ISSUE TITLE
Compile-time calculation for type family Min ,Max, (++), Take etc.

### ISSUE THREAD

**Issue by SkorikGG** [ekmett/constraints#53]
Will the implementation of the compile-time calculation for new type families in the modules Data.Constraint.Nat and Data.Constraint.Symbol?

Now
`> :t (Proxy::Proxy (Min 1 2))`
`(Proxy::Proxy (Min 1 2)) :: Proxy (Min 1 2)`

I would like to
`> :t (Proxy::Proxy (Min 1 2))`
`(Proxy::Proxy (Min 1 2)) :: Proxy 1`

**Comment by RyanGlScott** [comment]
@SkorikGG: I don't think `Data.Constraint.Nat` is ever going to support that. The magic in that module relies on a `reflection`-style trick at the value level to witness certain constraints, so you're only ever be able to use the axioms in `Data.Constraint.Nat` by pattern-matching against those witnesses.

That being said, you can do what you seek (a type-level `Min` calculation) with the `ghc-typelits-extra` package. For example:

```
$ ghci -fplugin GHC.TypeLits.Extra.Solver -XDataKinds
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
λ> :m + Data.Proxy GHC.TypeLits.Extra
λ> :t (Proxy::Proxy (Min 1 2))
(Proxy::Proxy (Min 1 2)) :: Proxy 1
```

**Comment by ekmett** [comment]
Unfortunately, this is out of scope for what we can offer without building a compiler plugin.
