### ISSUE TITLE
"Deferred type error" in runtime

### ISSUE THREAD

**Issue by SkorikGG** [ekmett/constraints#55]
With idempotent axioms and some other there is an strange error in runtime. For example
```
{-# LANGUAGE GADTs,PolyKinds,TypeApplications,DataKinds,TypeOperators,ScopedTypeVariables #-}

import Data.Constraint
import Data.Constraint.Nat
import GHC.TypeLits

newtype GF (n :: Nat) = GF Integer deriving Show

instance KnownNat n => Num (GF n) where
  xf@(GF x) + GF y = GF $ (x+y) `mod` (natVal xf)
  xf@(GF x) - GF y = GF $ (x-y) `mod` (natVal xf)
  xf@(GF x) * GF y = GF $ (x*y) `mod` (natVal xf)
  abs = id
  signum xf@(GF x) | x==0 = xf
                   | otherwise = GF 1
  fromInteger = GF

x :: GF 5
x = GF 3

y :: GF 5
y = GF 4

foo :: (KnownNat m, KnownNat n) => GF m -> GF n -> GF (Lcm m n)
foo m@(GF x) n@(GF y) = GF $ (x*y) `mod` (lcm (natVal m) (natVal n))

bar :: (KnownNat m)  => GF m -> GF m -> GF m
bar (x :: GF m) y = foo x y - foo y x \\ Sub @() (lcmIsIdempotent @m) \\ lcmNat @m @m 

z :: GF 5
z = bar x y

main = print z
```
This code is compiled, but when it runs, it produces the following error
```
Main.EXE: Main.hs:32:31: error:
    * Could not deduce: m ~ Lcm m m
      from the context: Lcm m m ~ m
        bound by a type expected by the context:
                   Lcm m m ~ m => GF m
        at Main.hs:32:21-69
      `m' is a rigid type variable bound by
        the type signature for:
          bar :: forall (m :: Nat). KnownNat m => GF m -> GF m -> GF m
        at Main.hs:31:8
      Expected type: GF m
        Actual type: GF (Lcm m m)
    * In the second argument of `(-)', namely `foo y x'
      In the first argument of `(\\)', namely `foo x y - foo y x'
      In the first argument of `(\\)', namely
        `foo x y - foo y x \\ Sub @() (lcmIsIdempotent @m)'
    * Relevant bindings include
        y :: GF m (bound at Main.hs:32:17)
        x :: GF m (bound at Main.hs:32:6)
        bar :: GF m -> GF m -> GF m (bound at Main.hs:32:1)
(deferred type error)
```
I found only such a crutch solution
```
{-# LANGUAGE GADTs,PolyKinds,TypeApplications,DataKinds,TypeOperators,ScopedTypeVariables #-}

import Data.Constraint
import Data.Constraint.Nat
import GHC.TypeLits
import Data.Type.Equality

newtype GF (n :: Nat) = GF Integer deriving Show

instance KnownNat n => Num (GF n) where
  xf@(GF x) + GF y = GF $ (x+y) `mod` (natVal xf)
  xf@(GF x) - GF y = GF $ (x-y) `mod` (natVal xf)
  xf@(GF x) * GF y = GF $ (x*y) `mod` (natVal xf)
  abs = id
  signum xf@(GF x) | x==0 = xf
                   | otherwise = GF 1
  fromInteger = GF

x :: GF 5
x = GF 3

y :: GF 5
y = GF 4

dictToRefl :: Dict (a ~ b) -> a :~: b
dictToRefl Dict = Refl

foo :: (KnownNat m, KnownNat n) => GF m -> GF n -> GF (Lcm m n)
foo m@(GF x) n@(GF y) = GF $ (x*y) `mod` (lcm (natVal m) (natVal n))

bar :: (KnownNat m)  => GF m -> GF m -> GF m
bar (x :: GF m) y = castWith (apply Refl $ dictToRefl lcmIsIdempotent) -- gcastWith don't work
                        (foo x y - foo y x) \\ lcmNat @m @m


z :: GF 5
z = bar x y

main = print z
```
P.S.  It would be desirable to include in the documentation information on the language extension
`TypeApplications`, without which it is impossible to use such axioms as `plusCommutes`.

**Comment by RyanGlScott** [comment]
The fact that you're only experiencing that error at runtime is a [GHC 8.0.2-specific bug](https://ghc.haskell.org/trac/ghc/ticket/13446). If you compile that original example in GHC 8.0.1 (or 8.2.1), you'll get a proper compilation error instead:

```
$ /opt/ghc/8.0.1/bin/ghci Bug.hsGHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
[1 of 1] Compiling Main             ( Bug.hs, interpreted )

Bug.hs:28:31: error:
    • Couldn't match type ‘m’ with ‘Lcm m m’
      ‘m’ is a rigid type variable bound by
        the type signature for:
          bar :: forall (m :: Nat). KnownNat m => GF m -> GF m -> GF m
        at Bug.hs:27:8
      Expected type: GF m
        Actual type: GF (Lcm m m)
    • In the second argument of ‘(-)’, namely ‘foo y x’
      In the first argument of ‘(\\)’, namely ‘foo x y - foo y x’
      In the first argument of ‘(\\)’, namely
        ‘foo x y - foo y x \\ Sub @() (lcmIsIdempotent @m)’
    • Relevant bindings include
        y :: GF m (bound at Bug.hs:28:17)
        x :: GF m (bound at Bug.hs:28:6)
        bar :: GF m -> GF m -> GF m (bound at Bug.hs:28:1)
```

**Comment by SkorikGG** [comment]
However, the question remains, how correctly to use `lcmIsIdempotent`.

**Comment by SkorikGG** [comment]
If your swap the `lcmIsIdempotent` and `lcmNat` in the `bar`:
```
bar (x :: GF m) y = foo x y - foo y x \\ lcmNat @m @m \\ Sub @() (lcmIsIdempotent @m)
```
you'll get a compillation error similar to runtime error:
```
Main.hs:32:31: error:
    * Could not deduce: m ~ Lcm m m
      from the context: Lcm m m ~ m
        bound by a type expected by the context:
                   Lcm m m ~ m => GF m
        at Main.hs:32:21-85
      `m' is a rigid type variable bound by
        the type signature for:
          bar :: forall (m :: Nat). KnownNat m => GF m -> GF m -> GF m
        at Main.hs:31:8
      Expected type: GF m
        Actual type: GF (Lcm m m)
    * In the second argument of `(-)', namely `foo y x'
      In the first argument of `(\\)', namely `foo x y - foo y x'
      In the first argument of `(\\)', namely
        `foo x y - foo y x \\ lcmNat @m @m'
    * Relevant bindings include
        y :: GF m (bound at Main.hs:32:17)
        x :: GF m (bound at Main.hs:32:6)
        bar :: GF m -> GF m -> GF m (bound at Main.hs:32:1)
```

The question remains, how to use such axioms as `lcmIsIdempotent`.

**Comment by RyanGlScott** [comment]
That error is quite strange—I would certainly expect that GHC could deduce `m ~ Lcm m m` from `Lcm m m ~ m`! This made me wonder if perhaps re-ordering the equality in `lcmIsIdempotent` would make a difference:

```diff
diff --git a/src/Data/Constraint/Nat.hs b/src/Data/Constraint/Nat.hs
index 6ac8e29..7fdd816 100644
--- a/src/Data/Constraint/Nat.hs
+++ b/src/Data/Constraint/Nat.hs
@@ -233,7 +233,7 @@ maxIsIdempotent = axiom
 gcdIsIdempotent :: forall n. Dict (Gcd n n ~ n)
 gcdIsIdempotent = axiom
 
-lcmIsIdempotent :: forall n. Dict (Lcm n n ~ n)
+lcmIsIdempotent :: forall n. Dict (n ~ Lcm n n)
 lcmIsIdempotent = axiom
 
 minDistributesOverPlus :: forall n m o. Dict ((n + Min m o) ~ Min (n + m) (n + o))
```

But that just makes it more obvious how bizarre the error is:

```
    • Could not deduce: m ~ Lcm m m
      from the context: m ~ Lcm m m
        bound by a type expected by the context:
                   m ~ Lcm m m => GF m
        at Bug.hs:28:21-85
      ‘m’ is a rigid type variable bound by
        the type signature for:
          bar :: forall (m :: Nat). KnownNat m => GF m -> GF m -> GF m
        at Bug.hs:27:8
      Expected type: GF m
        Actual type: GF (Lcm m m)
    • In the second argument of ‘(-)’, namely ‘foo y x’
      In the first argument of ‘(\\)’, namely ‘foo x y - foo y x’
      In the first argument of ‘(\\)’, namely
        ‘foo x y - foo y x \\ lcmNat @m @m’
    • Relevant bindings include
        y :: GF m (bound at Bug.hs:28:17)
        x :: GF m (bound at Bug.hs:28:6)
        bar :: GF m -> GF m -> GF m (bound at Bug.hs:28:1)
```

The only clue I have to what is going on is that enabling `-fprint-explicit-kinds` gives a slightly more informative error:

```
    • Could not deduce: (m :: Nat) ~~ (Lcm m m :: Nat)
      from the context: m ~ Lcm m m
```

So it appears that something fishy with heterogeneous equality is going on. Regardless, I'm pretty convinced there's another GHC bug lurking here. I'll investigate further.

**Comment by RyanGlScott** [comment]
I've opened [GHC Trac #13674](https://ghc.haskell.org/trac/ghc/ticket/13674) for this issue.

**Comment by RyanGlScott** [comment]
goldfire points out in https://ghc.haskell.org/trac/ghc/ticket/13674#comment:5 that the original program here is actually wrong in some sense (the confusing error message is just obfuscating the true error). We are attempting to use:

```haskell
lcmIsIdempotent @m :: Dict (m ~ Lcm m m)
```

But this will never work. The reason is that `Lcm` is defined to be an empty type family:

```haskell
type family Lcm :: Nat -> Nat -> Nat where
```

And as a result, `Lcm m m` will never reduce as a type. The only thing that `constraints` does with `Lcm` is use a reflection-style trick so that calling `natVal` on an `Lcm` type will sometimes give you back the actual result of evaluating `lcm` on two `Nat`s at the value level. But this cannot work on the type level with the machinery that `constraints` has, so `Lcm m m` will never reduce _as a type_.

With this in mind, let's reexamine `m ~ Lcm m m`. Because `Lcm m m` won't reduce, this violates the occurs check! So GHC is fully justified in rejecting this program.

However, this raises an interesting question: since it's impossible to actually use `lcmIsIdempotent` _et al._ due to this occurs-check limitation, should `constraints` even bother defining them? Maybe @ekmett had a different purpose in mind for them, but I don't see how one can possibly use them in idiomatic `constraints` code.

**Comment by SkorikGG** [comment]
If the GCH rejects `Lcm m m ~ m` then why does this code work?
```
dictToRefl :: Dict (a ~ b) -> a :~: b
dictToRefl Dict = Refl
castWith (apply Refl $ dictToRefl lcmIsIdempotent) (GF 0 :: GF (Lcm 2 2)) :: GF 2
```

**Comment by RyanGlScott** [comment]
@SkorikGG, that's a good observation. I've made a comment on the GHC Trac ticket [here](https://ghc.haskell.org/trac/ghc/ticket/13674#comment:7) asking the same question.

**Comment by SkorikGG** [comment]
If you define types  families as
```
type family Min (m::Nat) (n::Nat) :: Nat where
type family Max (m::Nat) (n::Nat) :: Nat where
type family Div (m::Nat) (n::Nat) :: Nat where
type family Mod (m::Nat) (n::Nat) :: Nat where
type family Gcd (m::Nat) (n::Nat) :: Nat where
type family Lcm (m::Nat) (n::Nat) :: Nat where
```
then there will be no compilation errors with idempotent axiom, although the type families are empty.
Due to future changes in the GHC, it will be safer to define type families as
```
type family Min (m::Nat) (n::Nat) :: Nat where
    Min m m = m
type family Max (m::Nat) (n::Nat) :: Nat where
    Max m m = m
type family Div (m::Nat) (n::Nat) :: Nat where
    Div m 1 = m
type family Mod (m::Nat) (n::Nat) :: Nat where
    Mod 0 m = 0
type family Gcd (m::Nat) (n::Nat) :: Nat where
    Gcd m m = m
type family Lcm (m::Nat) (n::Nat) :: Nat where
   Lcm m m = m
```
and remove idempotent axioms.

**Comment by ekmett** [comment]
I'd be willing to eta-expand the Lcm etc. type families.

It means we can't talk about `Lcm` unapplied, but meh, that currently doesn't arise.

Does this just delay us finding similar issues for the other axioms where m /= n, though?

Alternately, downgrading them from closed type families to type families, and putting in the type instance for Min m m = m seems about as useful and permits other laws of similar "shape" to be folded into the type family directly where possible.

**Comment by RyanGlScott** [comment]
I agree that adding explicit cases for `Min m m = m` and others as @SkorikGG suggests in https://github.com/ekmett/constraints/issues/55#issuecomment-300915249 is probably the most prudent solution. (It's what the `ghc-typelits-extra` GHC plugin does with its magical type families, as another data point.)

**Comment by ekmett** [comment]
Sold.

**Comment by RyanGlScott** [comment]
BTW @SkorikGG, goldfire answered your question in https://github.com/ekmett/constraints/issues/55#issuecomment-300767277 here in [the Trac ticket](https://ghc.haskell.org/trac/ghc/ticket/13674#comment:9). I'd try to summarize, but I don't think I could do a better job explaining it that he does.
