### ISSUE TITLE
Semigroup-Monoid-Proposal

### ISSUE THREAD

**Issue by ggreif** [ekmett/constraints#69]
needed for GHC 8.4 is not implemented. Causes compile errors with GHC HEAD.

**Comment by RyanGlScott** [comment]
Indeed. In the interim, I'm using [`head.hackage`](https://github.com/hvr/head.hackage) to build packages with GHC HEAD (there's currently a patch for [`constraints`](https://github.com/hvr/head.hackage/blob/41fb00374c3c6f518e8644cb15e498530dad05e9/patches/constraints-0.9.1.patch) there as well).

I think we'll hold off on releasing a new version to Hackage until 8.4-rc1 drops, as I don't like pumping out releases to match GHC HEAD, which is a moving target.

**Comment by RyanGlScott** [comment]
On second thought, most of these changes are simply `Semigroup`-related in nature, so I don't think there's any harm in releasing now. In fact, I've done just that with [`constraints-0.10`](http://hackage.haskell.org/package/constraints-0.10).
