### ISSUE TITLE
Class instances

### ISSUE THREAD

**Issue by coot** [ekmett/constraints#87]
I am interested in adding a few `Class` instances of the form:
```
instance Class (Functor f) (Functor f) ...
instance Class (Applicative f) (Applicative f) ...
```

Is there a good reason against adding them? It would require dropping the functional dependency `Class f g | g -> f`, so the natural question is if this functional dependency is necessary?

**Comment by sjoerdvisscher** [comment]
Can you explain why you want these instances?

**Comment by coot** [comment]
They are useful for providing instances for the following type:
```
newtype Free1 (c :: (Type -> Type) -> Constraint)
              (f ::  Type -> Type)
              a
      = Free1 {
          runFree1 :: forall g. c g => (forall x. f x -> g x) -> g a
        }
```
[Here](https://github.com/coot/free-algebras/pull/12/files#diff-55443d16a8e931820a40ce42d362641aR597) are some instances using quantified constraints and `Implies` class which like `Class`, but has the additional instances. It's unfortunate that  type class system does not allow to build such hierarchy using transitivity.

**Comment by sjoerdvisscher** [comment]
You can do that like this:

```
instance (forall x. c x => Functor x) => Functor (Free1 c f)
```

like I did here:

https://hackage.haskell.org/package/free-functors-1.0.1/docs/src/Data.Functor.HFree.html#line-78

**Comment by coot** [comment]
That's nice, thanks a bunch for the tip!
